2025-06-11 17:29:35,536 - DEBUG -  ... ingresando a la persistencia de datos ... 
2025-06-11 17:29:35,536 - DEBUG - ... se va a procesar en JSON 1 ... 
2025-06-11 17:29:35,536 - DEBUG -  ... SE VAN A PERSISTIR 189 PREGUNTAS CERRADAS EN LA BASE DE DATOS ...
2025-06-11 17:29:35,537 - DEBUG - 
üìå [1/189] Procesando un mensaje que es pregunta: buenas tardes, que deber√≠a tildar para instalar intellij correctamente. del autor feinez_
2025-06-11 17:29:35,537 - DEBUG - Se inserta o se obtiene autor
2025-06-11 17:29:35,539 - DEBUG - ‚ùå Error al persistir las preguntas y respuestas: no existe la relaci√≥n ¬´autores¬ª
LINE 1: SELECT id_autor FROM autores WHERE nombre_autor = 'feinez_'
                             ^

2025-06-11 17:29:35,543 - DEBUG - Traceback (most recent call last):
  File "c:\Users\lourd\Downloads\python_con_json\obtener_preguntas_y_respuestas\src\database\knowledge_base\data_base\clase_cargar_bdd.py", line 138, in persistir_preguntas
    autor_id = self.insertar_o_obtener_autor(pregunta.autor)
  File "c:\Users\lourd\Downloads\python_con_json\obtener_preguntas_y_respuestas\src\database\knowledge_base\data_base\clase_cargar_bdd.py", line 31, in insertar_o_obtener_autor
    cur.execute("SELECT id_autor FROM autores WHERE nombre_autor = %s", (nombre_autor,))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lourd\Downloads\python_con_json\obtener_preguntas_y_respuestas\venv\Lib\site-packages\psycopg2\extras.py", line 236, in execute
    return super().execute(query, vars)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: no existe la relaci√≥n ¬´autores¬ª
LINE 1: SELECT id_autor FROM autores WHERE nombre_autor = 'feinez_'
                             ^


2025-06-11 17:29:35,543 - DEBUG - ‚õî Transacci√≥n revertida debido al error.
2025-06-11 17:29:35,558 - DEBUG -  ... ingresando a la persistencia de datos ... 
2025-06-11 17:29:35,558 - DEBUG - ... se va a procesar en JSON 2 ... 
2025-06-11 17:29:35,558 - DEBUG -  ... SE VAN A PERSISTIR 153 PREGUNTAS CERRADAS EN LA BASE DE DATOS ...
2025-06-11 17:29:35,559 - DEBUG - 
üìå [1/153] Procesando un mensaje que es pregunta: buenas, que tal? no pude acceder al repo del equipo, intente entrando desde https://github.com/dds-utn/2024-tpa-mi-no-grupo-15
la clase que se unieron al repo no pude asistir, y cuando intente despues no pude del autor gonza3843
2025-06-11 17:29:35,559 - DEBUG - Se inserta o se obtiene autor
2025-06-11 17:29:35,559 - DEBUG - ‚ùå Error al persistir las preguntas y respuestas: no existe la relaci√≥n ¬´autores¬ª
LINE 1: SELECT id_autor FROM autores WHERE nombre_autor = 'gonza3843...
                             ^

2025-06-11 17:29:35,560 - DEBUG - Traceback (most recent call last):
  File "c:\Users\lourd\Downloads\python_con_json\obtener_preguntas_y_respuestas\src\database\knowledge_base\data_base\clase_cargar_bdd.py", line 138, in persistir_preguntas
    autor_id = self.insertar_o_obtener_autor(pregunta.autor)
  File "c:\Users\lourd\Downloads\python_con_json\obtener_preguntas_y_respuestas\src\database\knowledge_base\data_base\clase_cargar_bdd.py", line 31, in insertar_o_obtener_autor
    cur.execute("SELECT id_autor FROM autores WHERE nombre_autor = %s", (nombre_autor,))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lourd\Downloads\python_con_json\obtener_preguntas_y_respuestas\venv\Lib\site-packages\psycopg2\extras.py", line 236, in execute
    return super().execute(query, vars)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: no existe la relaci√≥n ¬´autores¬ª
LINE 1: SELECT id_autor FROM autores WHERE nombre_autor = 'gonza3843...
                             ^


2025-06-11 17:29:35,561 - DEBUG - ‚õî Transacci√≥n revertida debido al error.
2025-06-11 17:29:35,570 - DEBUG -  ... ingresando a la persistencia de datos ... 
2025-06-11 17:29:35,570 - DEBUG - ... se va a procesar en JSON 3 ... 
2025-06-11 17:29:35,570 - DEBUG -  ... SE VAN A PERSISTIR 137 PREGUNTAS CERRADAS EN LA BASE DE DATOS ...
2025-06-11 17:29:35,571 - DEBUG - 
üìå [1/137] Procesando un mensaje que es pregunta: hola profe, buenos d√≠as. ten√≠a una consulta sobre el material de lectura para la segunda clase (03/04/2024). ¬ølo estar√≠an subiendo en estos d√≠as? muchas gracias y felices pascuas üòÑ del autor martinsintas
2025-06-11 17:29:35,571 - DEBUG - Se inserta o se obtiene autor
2025-06-11 17:29:35,572 - DEBUG - ‚ùå Error al persistir las preguntas y respuestas: no existe la relaci√≥n ¬´autores¬ª
LINE 1: SELECT id_autor FROM autores WHERE nombre_autor = 'martinsin...
                             ^

2025-06-11 17:29:35,573 - DEBUG - Traceback (most recent call last):
  File "c:\Users\lourd\Downloads\python_con_json\obtener_preguntas_y_respuestas\src\database\knowledge_base\data_base\clase_cargar_bdd.py", line 138, in persistir_preguntas
    autor_id = self.insertar_o_obtener_autor(pregunta.autor)
  File "c:\Users\lourd\Downloads\python_con_json\obtener_preguntas_y_respuestas\src\database\knowledge_base\data_base\clase_cargar_bdd.py", line 31, in insertar_o_obtener_autor
    cur.execute("SELECT id_autor FROM autores WHERE nombre_autor = %s", (nombre_autor,))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lourd\Downloads\python_con_json\obtener_preguntas_y_respuestas\venv\Lib\site-packages\psycopg2\extras.py", line 236, in execute
    return super().execute(query, vars)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: no existe la relaci√≥n ¬´autores¬ª
LINE 1: SELECT id_autor FROM autores WHERE nombre_autor = 'martinsin...
                             ^


2025-06-11 17:29:35,573 - DEBUG - ‚õî Transacci√≥n revertida debido al error.
