2025-05-28 22:32:35,617 - DEBUG -  ... PERSISTENCIA DE DATOS ... 
2025-05-28 22:32:35,617 - DEBUG - ... PROCESAMIENTO DEL JSON 1 ... 
2025-05-28 22:32:35,618 - DEBUG -  ... SE VAN A PERSISTIR 189 PREGUNTAS CERRADAS EN LA BASE DE DATOS ...
2025-05-28 22:32:35,618 - DEBUG - 
üìå [1/189] Procesando PREGUNTA: 'buenas tardes, que deber√≠a tildar para instalar intellij correctamente.' . AUTOR: 'feinez_'
2025-05-28 22:32:35,625 - DEBUG - ‚ùå Error al persistir las preguntas y respuestas: no existe la relaci√≥n ¬´autores¬ª
LINE 1: SELECT id_autor FROM autores WHERE nombre_autor = 'feinez_'
                             ^

2025-05-28 22:32:35,627 - DEBUG - Traceback (most recent call last):
  File "c:\Users\lourd\Downloads\python_con_json\obtener_preguntas_y_respuestas\src\database\knowledge_base\data_base\clase_cargar_bdd.py", line 136, in persistir_preguntas
    autor_id = self.insertar_o_obtener_autor(pregunta.autor)
  File "c:\Users\lourd\Downloads\python_con_json\obtener_preguntas_y_respuestas\src\database\knowledge_base\data_base\clase_cargar_bdd.py", line 30, in insertar_o_obtener_autor
    cur.execute("SELECT id_autor FROM autores WHERE nombre_autor = %s", (nombre_autor,))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lourd\Downloads\python_con_json\obtener_preguntas_y_respuestas\venv\Lib\site-packages\psycopg2\extras.py", line 236, in execute
    return super().execute(query, vars)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: no existe la relaci√≥n ¬´autores¬ª
LINE 1: SELECT id_autor FROM autores WHERE nombre_autor = 'feinez_'
                             ^


2025-05-28 22:32:35,628 - DEBUG - ‚õî Transacci√≥n revertida debido al error.
2025-05-28 22:32:35,634 - DEBUG -  ... PERSISTENCIA DE DATOS ... 
2025-05-28 22:32:35,634 - DEBUG - ... PROCESAMIENTO DEL JSON 2 ... 
2025-05-28 22:32:35,634 - DEBUG -  ... SE VAN A PERSISTIR 153 PREGUNTAS CERRADAS EN LA BASE DE DATOS ...
2025-05-28 22:32:35,636 - DEBUG - 
üìå [1/153] Procesando PREGUNTA: 'buenas, que tal? no pude acceder al repo del equipo, intente entrando desde https://github.com/dds-utn/2024-tpa-mi-no-grupo-15
la clase que se unieron al repo no pude asistir, y cuando intente despues no pude' . AUTOR: 'gonza3843'
2025-05-28 22:32:35,637 - DEBUG - ‚ùå Error al persistir las preguntas y respuestas: no existe la relaci√≥n ¬´autores¬ª
LINE 1: SELECT id_autor FROM autores WHERE nombre_autor = 'gonza3843...
                             ^

2025-05-28 22:32:35,638 - DEBUG - Traceback (most recent call last):
  File "c:\Users\lourd\Downloads\python_con_json\obtener_preguntas_y_respuestas\src\database\knowledge_base\data_base\clase_cargar_bdd.py", line 136, in persistir_preguntas
    autor_id = self.insertar_o_obtener_autor(pregunta.autor)
  File "c:\Users\lourd\Downloads\python_con_json\obtener_preguntas_y_respuestas\src\database\knowledge_base\data_base\clase_cargar_bdd.py", line 30, in insertar_o_obtener_autor
    cur.execute("SELECT id_autor FROM autores WHERE nombre_autor = %s", (nombre_autor,))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lourd\Downloads\python_con_json\obtener_preguntas_y_respuestas\venv\Lib\site-packages\psycopg2\extras.py", line 236, in execute
    return super().execute(query, vars)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: no existe la relaci√≥n ¬´autores¬ª
LINE 1: SELECT id_autor FROM autores WHERE nombre_autor = 'gonza3843...
                             ^


2025-05-28 22:32:35,638 - DEBUG - ‚õî Transacci√≥n revertida debido al error.
2025-05-28 22:32:35,642 - DEBUG -  ... PERSISTENCIA DE DATOS ... 
2025-05-28 22:32:35,642 - DEBUG - ... PROCESAMIENTO DEL JSON 3 ... 
2025-05-28 22:32:35,642 - DEBUG -  ... SE VAN A PERSISTIR 137 PREGUNTAS CERRADAS EN LA BASE DE DATOS ...
2025-05-28 22:32:35,643 - DEBUG - 
üìå [1/137] Procesando PREGUNTA: 'hola profe, buenos d√≠as. ten√≠a una consulta sobre el material de lectura para la segunda clase (03/04/2024). ¬ølo estar√≠an subiendo en estos d√≠as? muchas gracias y felices pascuas üòÑ' . AUTOR: 'martinsintas'
2025-05-28 22:32:35,644 - DEBUG - ‚ùå Error al persistir las preguntas y respuestas: no existe la relaci√≥n ¬´autores¬ª
LINE 1: SELECT id_autor FROM autores WHERE nombre_autor = 'martinsin...
                             ^

2025-05-28 22:32:35,644 - DEBUG - Traceback (most recent call last):
  File "c:\Users\lourd\Downloads\python_con_json\obtener_preguntas_y_respuestas\src\database\knowledge_base\data_base\clase_cargar_bdd.py", line 136, in persistir_preguntas
    autor_id = self.insertar_o_obtener_autor(pregunta.autor)
  File "c:\Users\lourd\Downloads\python_con_json\obtener_preguntas_y_respuestas\src\database\knowledge_base\data_base\clase_cargar_bdd.py", line 30, in insertar_o_obtener_autor
    cur.execute("SELECT id_autor FROM autores WHERE nombre_autor = %s", (nombre_autor,))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lourd\Downloads\python_con_json\obtener_preguntas_y_respuestas\venv\Lib\site-packages\psycopg2\extras.py", line 236, in execute
    return super().execute(query, vars)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: no existe la relaci√≥n ¬´autores¬ª
LINE 1: SELECT id_autor FROM autores WHERE nombre_autor = 'martinsin...
                             ^


2025-05-28 22:32:35,645 - DEBUG - ‚õî Transacci√≥n revertida debido al error.
